const Categories = [
    "Infrastructure",
    "Health",
    "Education",
    "Transport",
    "Utilities",
    "Public Safety",
    "Environment",
    "Housing",
    "Economic Development",
    "Recreation",
    "Social Services",
    "Technology",
    "Agriculture",
    "Tourism",
    "Arts & Culture",
    "Water Management",
    "Waste Management",
    "Public Policy",
    "Labor & Employment",
    "Energy",
    "Urban Planning",
    "Disaster Management",
    "Immigration",
    "Law & Order",
    "Consumer Affairs",
    "Digital Services",
    "Civic Engagement",
    "Public Administration",
    "Sports & Recreation",
    "Senior Services",
    "Child Welfare",
    "Mental Health",
    "Environmental Protection",
    "Transportation Safety",
    "Road Safety",
    "Air Quality",
    "Noise Control",
    "Industrial Regulation",
    "Food & Nutrition",
    "Community Development",
    "Public Finance",
    "Taxation",
    "Employment Services",
    "Infrastructure Maintenance",
    "Rural Development",
    "Digital Transformation",
    "Small Business Support",
    "Trade & Commerce",
    "Emergency Services",
    "Public Works",
    "Cultural Heritage",
    "Green Energy",
    "Water Conservation",
    "Public Transit",
    "Technology Innovation",
    "Local Governance",
    "Sustainability",
    "Urban Renewal",
    "Citizen Safety",
    "Disability Services",
    "Family Services",
    "Youth Programs",
    "Economic Policy",
    "International Relations"
  ];
  
  export default Categories;