import React, { useEffect } from 'react';

const Chat = () => {
  useEffect(() => {
    const script = document.createElement('script');
    script.src = 'https://askelliebots.blob.core.windows.net/askelliefiles/widget-integration-140.js';
    script.async = true;

    script.onload = () => {
      const placeholderDiv = document.getElementById('script-placeholder');
      const newElement = document.createElement('div');
      newElement.textContent = 'Content generated by the script';
      placeholderDiv.appendChild(newElement);
    };

    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  return (
    <div className="app">
      {/* Your component content goes here */}
      <div
        id="script-container"
        style={{
          position: 'fixed',
          bottom: '6vh',
          left: 0,
          right: 0,
          display: 'flex',
          justifyContent: 'center',
        }}
      >
        <div id="script-placeholder" />
      </div>
    </div>
  );
};

export default Chat;